### ISSUE TITLE
403 error when authenticating

### ISSUE THREAD

**Issue by matenia** [jeffkreeftmeijer/tumblr#4]
Hi All,

I have installed and followed the instructions, put in the right user information in the user object and i get a 403 error when attempting to post a blog (error in authentication)

Any ideas at all?
Is there a gem version dependency that i should be aware of?

Code Snippets:

<pre><code>#declare user
tumblruser = Tumblr::User.new('validusername', 'validpassword')
#post from an object
post = Tumblr::Post.create(tumblruser, :type => 'video', :embed => @post.video_html, :caption => @post.content)</code></pre>

Thanks, Matenia Rossides

**Comment by tobynet** [comment]
I have same problem. 

There are 2 problems and 2 reasons.
- "tumblr-api" gem assumes "httparty" ver 0.4.3, 
- but installed "httparty"  is 0.5.2(not assumed) with "gem install tumblr-api", and require httparty 0.5.2(not assumed) with "requirie 'tumblr'"

reasons:
- because not specified "httparty" gem version dependency  in gemspec
- and 'gem 'httparty', "<= 4.3" ' is mistaken in tumblr.rb  (not "<= 4.3", correct is "<= 0.4.3")

wait fixed patch or do adhock solution.

adhock solution:
- uninstall new  httparty greater than 0.4.3 (ex. gem uninstall httparty -v "0.5.2"; gem install httparty -v "0.4.3")
- or edit and fixed in tumblr.rb like following.

-gem 'httparty', "<= 4.3" 
+gem 'httparty', "<= 0.4.3"

**Comment by matenia** [comment]
Thanks, worked like a charm
